### ISSUE TITLE
导出默认值问题

### ISSUE THREAD

**Issue by jianyan74** [e282486518/yii2-console-migration#6]
如果字段设置了无符号并且默认值为空  无符号的默认值会被判断不出来导致导入数据库默认值没有了

在 e282486518\migration\components\MigrateCreate类第246行改成这样子就可以了
 ` if(is_int($column->defaultValue) || !empty($column->defaultValue) || $column->defaultValue == '' || $column->defaultValue == '0')`

**Comment by jianyan74** [comment]
这个问题不处理了麽......

**Comment by e282486518** [comment]
} elseif (is_null($column->defaultValue)) {
    $fields .= " DEFAULT NULL";
}
加了个这个~~

**Comment by jianyan74** [comment]
不单单是这个 如果设置了无符号且有默认值也会丢失，我是在int类型下测试的，tinyint倒是没有这个问题

**Comment by jianyan74** [comment]
int 无符号 默认0 你可以试一下

**Comment by jianyan74** [comment]
is_int($column->defaultValue) || !empty($column->defaultValue) || $column->defaultValue == '' 这一段判断不了 '0' (字符串类型的0)

**Comment by e282486518** [comment]
将你的数据表的上去了发我一下吧，我这边是没问题的

这个是我导出的
'create_time' => 'int(10) unsigned NOT NULL DEFAULT \'0\' COMMENT \'创建时间\'',

**Comment by jianyan74** [comment]
```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for rf_sys_menu_cate_copy
-- ----------------------------
DROP TABLE IF EXISTS `rf_sys_menu_cate_copy`;
CREATE TABLE `rf_sys_menu_cate_copy`  (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `pid` int(10) UNSIGNED NULL DEFAULT 0 COMMENT '上级id',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '系统_菜单分类表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by jianyan74** [comment]
```
        $this->createTable('{{%sys_menu_cate_copy}}', [
            'id' => "int(10) NOT NULL AUTO_INCREMENT COMMENT '主键'",
            'pid' => "int(10) unsigned NULL COMMENT '上级id'",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='系统_菜单分类表'");
```
导出之后就变成这样子了

**Comment by e282486518** [comment]
我这边返回的是这个，与你的不一样：
```php
'id' => "int(10) NOT NULL AUTO_INCREMENT COMMENT '主键'",
'pid' => "int(10) unsigned NULL DEFAULT '0' COMMENT '上级id'
```
你看一下你这个插件是不是最新的。
或者，你在插件中手动输出调试一下 `$column->defaultValue`看其类型是int还是其他，我这里是int的所以可以判断

**Comment by jianyan74** [comment]
Yii Migration Tool (based on Yii v2.0.22)

string(1) "0"

打印出来是 string 0
所以 我改成这样子就ok 
is_int($column->defaultValue) || !empty($column->defaultValue) || $column->defaultValue == '' || $column->defaultValue == '0'

**Comment by e282486518** [comment]
你的MySQL版本是什么？

**Comment by jianyan74** [comment]
5.7.17，我估计很大部分原因是因为mysql查出的int型字段都是string 
https://www.cnblogs.com/-mrl/p/10593527.html 需要转才能变成int

**Comment by jianyan74** [comment]
所以加上 $column->defaultValue == '0'这句话就可以避免这个问题

**Comment by e282486518** [comment]
已经加上了~~谢了~

**Comment by jianyan74** [comment]
记得更新后打个包哈 我去更新下

**Comment by e282486518** [comment]
ok~

**Comment by jianyan74** [comment]
packagist 还是1.3.0的....

**Comment by e282486518** [comment]
已经更新到了1.3.1了
